<?php
// $Id: sos.module,v 0.1 2011/02/20 04:56:47 blackoutjack Exp $

/**
 * @file
 * Primary module file for Simple Open Singlesignon 
 *
 * Logs in a user simultaneously to a group of domains linked together with the domain_access module
 */	

// Some utility functions and configuration constants
include_once 'sos.util.inc';

// Functions for communicating with other sites
include_once 'sos.comm.inc';



/**
 * Implementation of hook_menu().
 */
function sos_menu() {
	// Administrative pages
	$items['admin/build/sos/configure'] = array(
		'title' => 'Simple Open Singlesignon',
		'description' => 'Enable single sign-on across all domains',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('sos_admin_settings'),
		'access arguments' => array('administer sos'),
		'file' => 'sos.admin.inc',
	);
	$items['admin/build/sos/sites'] = array(
		'title' => 'Simple Open Singlesignon Sites',
		'description' => 'View a list of sites in the SOS ring',
		'page callback' => 'sos_sites_list',
		'access arguments' => array('administer sos'),
		'file' => 'sos.admin.inc',
	);
	$items['admin/build/sos/sites/add'] = array(
		'title' => 'Add Simple Open Singlesignon Site',
		'description' => 'Manually add a new site to the SOS ring',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('sos_site_edit_form'),
		'access arguments' => array('administer sos'),
		'file' => 'sos.admin.inc',
	);
	$items['admin/build/sos/sites/edit/%'] = array(
		'title' => 'Add Simple Open Singlesignon Site',
		'description' => 'Edit an existing SOS site',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('sos_site_edit_form', 5),
		'access arguments' => array('administer sos'),
		'file' => 'sos.admin.inc',
	);
	$items['admin/build/sos/sites/delete/%'] = array(
		'title' => 'Remove Simple Open Singlesignon Site',
		'description' => 'Delete an existing SOS site',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('sos_site_delete_form', 5),
		'access arguments' => array('administer sos'),
		'file' => 'sos.admin.inc',
	);
	$items['sos/generator/%'] = array(
		'page callback' => 'sos_ahah_generate_key',
		'page arguments' => array(2),
		'access arguments' => array('administer sos'),
		'file' => 'sos.admin.inc',
		'type' => MENU_CALLBACK,
	);

	// COMMUNICATION_ENDPOINT defined in sos.comm.inc
	$items[COMMUNICATION_ENDPOINT] = array(
		'title' => 'Simple Open Singlesignon Site Registration',
		'description' => 'Target page for a remote site that want to communicate with this one',
		'page callback' => 'sos_register_remote_domain',
		'page arguments' => array(2,3),
		'access arguments' => array('access sos'), // %%% some way to check access here?
		'file' => 'sos.reception.inc'
	);
	$items['sos/set-cookie'] = array(
		'title' => 'Simple Open Singlesignon',
		'description' => 'Set single sign-on cookie on client for cross-domain login',
		'page callback' => 'sos_set_cookie',
		'access arguments' => array('access sos'),
	);
	$items['sos/logo'] = array(
		'title' => 'Simple Open Singlesignon',
		'description' => 'Setting single sign-on cookie for cross-domain login',
		'page callback' => 'sos_logo',
		'access arguments' => array('access sos'),
	);

	return $items;
}


/**
 * Implementation of hook_boot().
 *
 * Retrieve or set up the global session id to be shared across SOS sites.
 *
 * This runs on all domains where the SOS module is enabled, so there are different execution paths
 * for a number of scenarios.
 *
 * 1. The first time a user (browser session) has accessed any page, a global_sid will be established.
 * 2. When a user visits the login page on domain A, the global_sid is passed via a GET parameter 
 *		to the other sites (see sos_form_alter@user_login).
 * 3. 
 * 
 */
function sos_boot() {
	$enabled = variable_get('sos_enabled', false);
	if (!$enabled) return;

	$sid = session_id();
	sess_write($sid, serialize($_SESSION));
	$global_sid = _sos_get_global_sid();

	// If global_sid is empty, there was an error during reconsiliation.
	if (empty($global_sid)) return;

	// Get the current domain id.
	// %%% move this stuff into sos.util.inc, and implement hmac checking
	$thisdom = domain_get_domain();
	$domain_id = $thisdom['domain_id'];

	// Update the database to allow the server to recognize session.
	db_query("UPDATE {sessions} SET sos_sid='%s',domain='%s',sos_nonce='%s' WHERE sid='%s'", $global_sid, $domain_id, $nonce, $sid);
	//watchdog('sos',"update {sessions} set sos_sid='%s',domain='%s',sos_nonce='%s' where sid='%s'", array($global_sid,$domain_id,$nonce,$sid), WATCHDOG_NOTICE);

	// Create and set the global cookie to allow the browser to recognize session.
	// Examine the normal session cookie to match most of its parameters.
	$sess_cookie = session_get_cookie_params();
	$cookie_domain = $sess_cookie['domain'];
	$lifetime = $sess_cookie['lifetime'];
	// Allow debugging, but otherwise this needs to be a secure cookie.
	$secure = FORCE_SSL;
	// %%% Restrict root URI based on Drupal setup.
	$root_uri = '/';
	setcookie(SOS_GLOBAL_SESSION_COOKIE, $global_sid, $lifetime, $root_uri, $cookie_domain, $secure);
}


/**
 * Implementation of hook_perm().
 */
function sos_perm() {
	return array('access sos', 'administer sos');
}

/**
 * Display the site logo directly and set a session cookie.
 */
function sos_logo() {
	$enabled = variable_get('sos_enabled', false);
	if (!$enabled) return;

	// The global_sid should have been populated during hook_boot.
	$global_sid = _sos_get_global_sid();
	
	$thisdom = domain_get_domain();
	$theme = domain_theme_lookup($thisdom['domain_id']);
	$theme_settings = unserialize($theme['settings']);
	
	$logo = $theme_settings['logo_path'];
	if (empty($logo)) {
		init_theme();
		$logo = theme_get_setting('logo');
		if (substr($logo, 0, 1) == '/') { // %%% not great
			$logo = substr($logo, 1);
		}
	}
	$filelength = filesize($logo);
	
	// %%% generalize to other image types
	header("Content-type: image/png");
	//header("Content-type: text/plain");
	header('Last-Modified: '.date('r'));
	header('Accept-Ranges: bytes');
	header('Content-Length: '.$filelength);

	readfile($logo);
	//var_dump($theme_settings);
	//echo $logo;


}

/**
 * Display the site logo within an iframe and set a session cookie.
 */
function sos_set_cookie() {
	$enabled = variable_get('sos_enabled', false);
	if (!$enabled) return;

	$global_sid = _sos_get_global_sid();

	$thisdom = domain_get_domain();
	$domain_id = $thisdom['domain_id'];

	// %%% hard code for the moment
	$logo = theme_get_setting('logo');
	$logo = "/sites/default/files/satara_logo.png";

	$scripts = drupal_get_js();

	echo '<html>'."\n";
	echo '<head>'."\n";
	echo $scripts;
	echo '<script type="text/javascript">'."\n";
	echo '$(document).ready(function () {'."\n";
	echo '	document.cookie = "'.SOS_GLOBAL_SESSION_COOKIE.'='.$global_sid.';";'."\n";
	echo '	if (document.cookie.indexOf("'.SOS_GLOBAL_SESSION_COOKIE.'=") == -1) {'."\n";
	echo '		msgdiv = $("#message");'."\n";
	echo '		msgdiv.text("Your browser does not allow 3rd-party cookies, so we won\'t be able to log you in to this site.");'."\n";
		echo '	}'."\n";
	echo '})'."\n";
	echo '</script>'."\n";
	echo '</head>'."\n";
	echo '<body>'."\n";
	echo '<div id="message"></div>'."\n";
	echo '<img src="'.$logo.'" />'."\n";
	echo '</body>'."\n";
	echo '</html>'."\n";

	exit;
}

/*
 * Invoked after the user has been authenticated (on the current site).
 */
function sos_user($op, &$edit, &$account, $category=null) {
	$enabled = variable_get('sos_enabled', false);
	if (!$enabled) return;

	switch ($op) {
		case 'login':
			// Get old global_sid from form_values array.
			$global_sid = $edit['sos_global_sid'];
			//$global_sid = _sos_get_global_sid(); // Empty because the session has been regenerated.
			
			// %%% Need to verify the global_sid somehow, for some reason?
			// Not generating a new one because GSID cookie should always be secure


			_sos_login_connected_sites($account, $global_sid);

			$sos_markup = '<p class="sos-message">'.t("You have also been logged in to the following sites.").'</p>';
			$sos_markup .= _sos_render_logos();	

			drupal_set_message($sos_markup);
			break;
		case 'logout':
			$global_sid = _sos_get_global_sid();

			drupal_set_message(var_export($account,true));
			_sos_logout_connected_sites($account, $global_sid);

			$sos_markup = '<p class="sos-message">'.t("You have also been logged out of the following sites.").'</p>';
			//$sos_markup .= _sos_render_logos();	

			drupal_set_message($sos_markup);
			break;
	
	}
}

/*
 * Get a site object representing the current/local site.
 */
function sos_get_local_site() {
	static $thissite;
	if ($thissite) return $thissite;

	// %%% is this good enough to use?
	$thisdomain = $_SERVER['SERVER_NAME'];

	$thissite = db_fetch_object(db_query("SELECT * FROM {sos_sites} WHERE subdomain='%s'", $thisdomain));
	
	return ($thissite);
}

/*
 * Get an array of objects from sos_sites table.
 */
function sos_get_all_active_sites() {
	static $sites;
	if ($sites) return $sites;
	
	$sites = array();
	$site_result = db_query("SELECT * FROM {sos_sites} WHERE status=1");
	while ($site = db_fetch_object($site_result)) {
		$sites[] = $site;
	}

	return $sites;
}

/*
 * Load an existing site by id.
 */
function sos_get_site($site_id) {
	$site = db_fetch_object(db_query("SELECT * FROM {sos_sites} WHERE site_id=%d", $site_id));
	
	return $site;
}

/*
 * Define the global SOS ID propagation blocks.
 */
/*
function sos_block($op, $delta, $edit = array()) {
	switch ($op) {
		case 'list':
			$blocks = array();

			$logoblock = array(
				'info' => "SOS Logo Block",
				'cache' => BLOCK_NO_CACHE,

			);

			return $blocks;

		case 'view':
			
			break;

}
*/

/**
 * Implementation of hook_form_alter().
 */
function sos_form_alter(&$form, $form_state, $form_id) {

	switch ($form_id) {
		case 'sos_admin_settings':
			$form['#cache'] = TRUE;
			break;
		case 'user_login':
		case 'user_login_block':
			//drupal_set_message(drupal_get_path('module', 'sos')."/sos.css");  // %%% wasn't working
			//drupal_add_css(drupal_get_path('sos', 'module')."/sos.css");
			$enabled = variable_get('sos_enabled', false);
			if (!$enabled) {
				return;
			}

			// %%% Make this message configurable.
			$sos_markup = '<p class="sos-message">'.t("You will also be logged into").'</p>';
			$sos_markup .= _sos_render_logos();
			$global_sid = _sos_get_global_sid();

			// Add the global_sid as a hidden field to be accessed by the submit handler.
			$form['sos_global_sid'] = array(
				"#type" => 'hidden',
				"#value" => $global_sid,
			);
			// Add the markup to the login form.
			$form['sos_sites'] = array(
				"#type" => 'markup',
				"#value" => $sos_markup,
				"#weight" => 500, // %%% Arbitrary, can check the current weights
			);
			$form['submit']["#weight"] = 499; // %%% Arbitrary

			break;
		case 'user_pass':
			// %%%
			break;
		case 'user_register':
			// Registration form also needs to be an "airlock" and make requests to the other sites.
			$sos_markup = '<p class="sos-message">'.t("You will also be able to use this account on").'</p>';
			$sos_markup .= _sos_render_logos();
			$global_sid = _sos_get_global_sid();

			// Add the global_sid as a hidden field to be accessed by the submit handler.
			$form['sos_global_sid'] = array(
				"#type" => 'hidden',
				"#value" => $global_sid,
			);
			// Add the markup to the login form.
			$form['sos_sites'] = array(
				"#type" => 'markup',
				"#value" => $sos_markup,
				"#weight" => 500, // %%% Arbitrary, can check the current weights
			);
			$form['submit']["#weight"] = 499; // %%% Arbitrary
			break;
		default:
			return;
	}

}

